### PR TITLE
Add deprecation warning banner in `README.md`

### PR DESCRIPTION
**Pull request by tomvothecoder**
Related to https://github.com/xCDAT/xcdat/issues/175

### CODE REVIEW

**Comment by tomvothecoder** [comment]
I disabled requiring at least 1 reviewer approval and passing status checks for TravisCI and CircleCI (both are no longer integrated so they won't work) before merging.

**Comment by tomvothecoder** [comment]
Hi @durack1, just wanted to get your feedback on this CDAT deprecation banner in the `README.md`.
https://github.com/CDAT/cdat/blob/deprecation-warning/README.md

I plan to add it to all of the repos listed here https://github.com/xCDAT/xcdat/issues/175#issuecomment-1078471843, as well as the CDAT official website.

**Comment by durack1** [comment]
@tomvothecoder looks great, some suggestions

```
The CDAT library and its sub-packages are in maintenance-only mode. We currently support Python versions 3.7,
3.8, 3.9, 3.10. We plan to deprecate the package, ceasing support around the end of calendar 2023. Until this
time, only package dependencies will be monitored to ensure the packages build and install in Conda
environments. Unfortunately, feature requests and bug fixes will no longer be addressed.
--
If you are interested in an alternative solution, please check out the
[xarray](https://anaconda.org/conda-forge/xarray) and
[xCDAT - Xarray extended with Climate Data Analysis Tools](https://anaconda.org/conda-forge/xcdat)
projects.
```

Not sure if you want to explicitly outline the supported packages, which I assume are `cdms2`, `cdat_info`, `cdutil`, `cdtime`, `genutil`, `libcdms`

**Comment by tomvothecoder** [comment]
Thanks @durack1.

Here's what I came up with using your suggestions:
 
> ⚠️ WARNING: Maintenance-only mode until around the end of 2023.
> --
> The CDAT library is now in maintenance-only mode, with  plans for deprecation and cease of support around the end of calendar  year 2023. Until this time, the dependencies for specific CDAT packages (cdms2, cdat_info, cdutil, cdtime, genutil, libcdms)  will be monitored to ensure they build and install in Conda  environments. We currently support Python versions 3.7, 3.8, 3.9, and  3.10. Unfortunately, feature requests and bug fixes will no longer be  addressed.
>
> If you are interested in an alternative solution, please check out the xarray and xCDAT - Xarray Extended With Climate Data Analysis Tools projects.

**Comment by durack1** [comment]
@tomvothecoder looks good to me! You may want to add a snippet as an issue template - the `Unfortunately, feature requests and bug fixes will no longer be addressed` is the key information - just to catch folks who expect support, but wont get it!

**Comment by tomvothecoder** [comment]
@durack1 Great idea. I added a GH issue template using the info from the banner.

**Pull request merged**
